/* Generated By:JavaCC: Do not edit this line. CronusGrammar.java */
package main;
import java.io.PrintStream;
import javax.management.BadStringOperationException;

public class CronusGrammar implements CronusGrammarConstants {
  public static void main(String args []) throws ParseException, TokenMgrError
  {
    CronusGrammar parser = new CronusGrammar(System.in);
    parser.Start(System.out);
  }

  final public void Start(PrintStream printStream) throws ParseException {
  String previousValue;
    printStream.println("New Graph");
    label_1:
    while (true) {
      if (jj_2_1(3)) {
        previousValue = NewGraph();
      printStream.println(previousValue);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NODE:
        case VARIABLE:
          previousValue = ListNodes();
      printStream.println(previousValue);
          break;
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GRAPH:
      case NODE:
      case EDGE:
      case VARIABLE:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    printStream.println("--- End of program ---");
  }

/**
 * Get graph
 */
  final public String NewGraph() throws ParseException {
  Token v;
  String graphVar, pathVar, valueLeft, valueRight = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
    case NODE:
    case EDGE:
      valueLeft = Declaration();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
        valueRight = NewGraphRight();
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s;", valueLeft);}
    else {if (true) return String.format("%s = %s;", valueLeft, valueRight);}
      break;
    case VARIABLE:
      v = jj_consume_token(VARIABLE);
    valueLeft = v.image;
      jj_consume_token(EQ);
      valueRight = NewGraphRight();
      jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s;", valueLeft);}
    else {if (true) return String.format("%s = %s;", valueLeft, valueRight);}
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Declaration of variables
 */
  final public String Declaration() throws ParseException {
  Token type, v;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
      type = jj_consume_token(GRAPH);
      break;
    case NODE:
      type = jj_consume_token(NODE);
      break;
    case EDGE:
      type = jj_consume_token(EDGE);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    v = jj_consume_token(VARIABLE);
    {if (true) return String.format("%s %s", type.image, v.image);}
    throw new Error("Missing return statement in function");
  }

  final public String NewGraphRight() throws ParseException {
  Token n, g, p, opar, cpar;
    n = jj_consume_token(NEW);
    g = jj_consume_token(GRAPH);
    opar = jj_consume_token(OPAR);
    p = jj_consume_token(PATH);
    cpar = jj_consume_token(CPAR);
    {if (true) return String.format("%s %s%s%s%s", n.image, g.image, opar.image, p.image, cpar.image);}
    throw new Error("Missing return statement in function");
  }

/**
 * List all nodes according two parameters (if any)
 */
  final public String ListNodes() throws ParseException {
  Token v;
  String graphVar, pathVar, valueLeft, valueRight = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NODE:
      valueLeft = NodeListDec();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
        valueRight = ListNodesRight();
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s;", valueLeft);}
    else {if (true) return String.format("%s = %s;", valueLeft, valueRight);}
      break;
    case VARIABLE:
      v = jj_consume_token(VARIABLE);
    valueLeft = v.image;
      jj_consume_token(EQ);
      valueRight = ListNodesRight();
      jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s;", valueLeft);}
    else {if (true) return String.format("%s = %s;", valueLeft, valueRight);}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Node list declaration
 */
  final public String NodeListDec() throws ParseException {
  Token n, obr, cbr, v;
    n = jj_consume_token(NODE);
    obr = jj_consume_token(OSQBR);
    cbr = jj_consume_token(CSQBR);
    v = jj_consume_token(VARIABLE);
    {if (true) return String.format("%s%s%s %s", n.image, obr.image, cbr.image, v.image);}
    throw new Error("Missing return statement in function");
  }

/**
 * Right side of declaration to get list of nodes
 */
  final public String ListNodesRight() throws ParseException {
  Token v, d, n, o, c;
  String parValue = null;
    v = jj_consume_token(VARIABLE);
    d = jj_consume_token(DOT);
    n = jj_consume_token(NODES);
    o = jj_consume_token(OPAR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
    case DEGREE:
    case OSQBR:
      if (jj_2_2(5)) {
        parValue = AllParametersNode();
      } else if (jj_2_3(2)) {
        parValue = TwoParametersNode();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LABEL:
        case DEGREE:
        case OSQBR:
          parValue = OneParameterNode();
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    c = jj_consume_token(CPAR);
    if (parValue == null) {if (true) return String.format("%s%s%s%s%s", v.image, d.image, n.image, o.image, c.image);}
    else {if (true) return String.format("%s%s%s%s%s%s", v.image, d.image, n.image, o.image, parValue, c.image);}
    throw new Error("Missing return statement in function");
  }

/**
 * Filter search node with all three parameters
 */
  final public String AllParametersNode() throws ParseException {
  Token comma;
  String returnValue, value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      returnValue = NodeLabel();
      comma = jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DEGREE:
        value = NodeDegree();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeProperties();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      case OSQBR:
        value = NodeProperties();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeDegree();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case DEGREE:
      returnValue = NodeDegree();
      comma = jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LABEL:
        value = NodeLabel();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeProperties();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      case OSQBR:
        value = NodeProperties();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeLabel();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case OSQBR:
      returnValue = NodeProperties();
      comma = jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LABEL:
        value = NodeLabel();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeDegree();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      case DEGREE:
        value = NodeDegree();
      returnValue += String.format("%s%s", comma.image, value);
        comma = jj_consume_token(COMMA);
        value = NodeLabel();
      returnValue += String.format("%s%s", comma.image, value);
      {if (true) return returnValue;}
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Filter search node with two parameters
 */
  final public String TwoParametersNode() throws ParseException {
  Token comma;
  String returnValue, value;
    returnValue = NodeLabel();
    comma = jj_consume_token(COMMA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEGREE:
      value = NodeDegree();
      break;
    case OSQBR:
      value = NodeProperties();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    returnValue += String.format("%s%s", comma.image, value);
    {if (true) return returnValue;}
    returnValue = NodeDegree();
    comma = jj_consume_token(COMMA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      value = NodeLabel();
      break;
    case OSQBR:
      value = NodeProperties();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    returnValue += String.format("%s%s", comma.image, value);
    {if (true) return returnValue;}
    returnValue = NodeProperties();
    comma = jj_consume_token(COMMA);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      value = NodeLabel();
      break;
    case DEGREE:
      value = NodeDegree();
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    returnValue += String.format("%s%s", comma.image, value);
    {if (true) return returnValue;}
    throw new Error("Missing return statement in function");
  }

/**
 * Filter search node with one parameter
 */
  final public String OneParameterNode() throws ParseException {
  Token comma;
  String valueLabel, valueDegree, valueProperties;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      valueLabel = NodeLabel();
    {if (true) return valueLabel;}
      break;
    case DEGREE:
      valueDegree = NodeDegree();
    {if (true) return valueDegree;}
      break;
    case OSQBR:
      valueProperties = NodeProperties();
    {if (true) return valueProperties;}
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Filter node parameter label
 */
  final public String NodeLabel() throws ParseException {
  Token label, eq;
  String value;
    label = jj_consume_token(LABEL);
    eq = jj_consume_token(EQ);
    value = Value();
    {if (true) return String.format("%s%s%s", label.image, eq.image, value);}
    throw new Error("Missing return statement in function");
  }

/**
 * Filter node parameter degree
 */
  final public String NodeDegree() throws ParseException {
  Token degree, eq, integer;
  String compare;
    degree = jj_consume_token(DEGREE);
    compare = CompareValues();
    {if (true) return String.format("%s%s", degree.image, compare);}
    throw new Error("Missing return statement in function");
  }

/**
 * Define ways to compare variable with values
 */
  final public String CompareValues() throws ParseException {
  Token eq, os, cs, comma, comp;
  String value, value2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      eq = jj_consume_token(EQ);
      os = jj_consume_token(OSQBR);
      value = Value();
      comma = jj_consume_token(COMMA);
      value2 = Value();
      cs = jj_consume_token(CSQBR);
    {if (true) return String.format("%s%s%s%s%s%s", eq.image, os.image, value, comma.image, value2, cs.image);}
      break;
    case COMP:
      comp = jj_consume_token(COMP);
      value = Value();
    {if (true) return String.format("%s%s", comp.image, value);}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Filter node parameter properties
 */
  final public String NodeProperties() throws ParseException {
  Token comma, osqbr, csqbr, key;
  String comp, returnValue;
    osqbr = jj_consume_token(OSQBR);
    key = jj_consume_token(VARIABLE);
    comp = CompareValues();
    returnValue = String.format("%s%s%s", osqbr.image, key.image, comp);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_2;
      }
      comma = jj_consume_token(COMMA);
      key = jj_consume_token(VARIABLE);
      comp = CompareValues();
      returnValue += String.format("%s %s%s", comma.image, key.image, comp);
    }
    csqbr = jj_consume_token(CSQBR);
    returnValue += csqbr.image;
    {if (true) return returnValue;}
    throw new Error("Missing return statement in function");
  }

/**
 * Types of values: string or number
 */
  final public String Value() throws ParseException {
  Token s, i, f;
  String value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      s = jj_consume_token(STRING);
    {if (true) return String.format("%s", s.image);}
      break;
    case INTEGER:
    case FLOAT:
      value = Number();
    {if (true) return String.format("%s", value);}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Number format: integer or float
 */
  final public String Number() throws ParseException {
  Token i, f;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER:
      i = jj_consume_token(INTEGER);
    {if (true) return String.format("%s", i.image);}
      break;
    case FLOAT:
      f = jj_consume_token(FLOAT);
    {if (true) return String.format("%s", f.image);}
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/**
 * Properties of a Node TODO - não está a ser usado
 */
  final public String GetNode() throws ParseException {
  Token v = null, eq = null, sc = null;
  String valueLeft = null, valueRight = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GRAPH:
    case NODE:
    case EDGE:
      valueLeft = Declaration();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        eq = jj_consume_token(EQ);
        valueRight = GetNodeRight();
        break;
      default:
        jj_la1[21] = jj_gen;
        ;
      }
      sc = jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s%s", valueLeft, sc.image);}
    else {if (true) return String.format("%s %s %s;", valueLeft, eq.image, valueRight);}
      break;
    case VARIABLE:
      v = jj_consume_token(VARIABLE);
    valueLeft = v.image;
      jj_consume_token(EQ);
      valueRight = GetNodeRight();
      jj_consume_token(SCOL);
    if (valueRight == null) {if (true) return String.format("%s%s", valueLeft, sc.image);}
    else {if (true) return String.format("%s %s %s;", valueLeft, eq.image, valueRight);}
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String GetNodeRight() throws ParseException {
  Token v, d, n, opar, i, cpar;
    v = jj_consume_token(VARIABLE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      d = jj_consume_token(DOT);
      n = jj_consume_token(NODEF);
      opar = jj_consume_token(OPAR);
      i = jj_consume_token(INTEGER);
      cpar = jj_consume_token(CPAR);
      {if (true) return String.format("%s%s%s%s%s%s", v.image, d.image, n.image, opar.image, i.image, cpar.image);}
      break;
    case OSQBR:
      opar = jj_consume_token(OSQBR);
      i = jj_consume_token(INTEGER);
      cpar = jj_consume_token(CSQBR);
      {if (true) return String.format("%s%s%s%s", v.image, opar.image, i.image, cpar.image);}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(COMP)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_5() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(EQ)) return true;
    if (jj_scan_token(OSQBR)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_5()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) return true;
    }
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(DEGREE)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_6() {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) jj_scanpos = xsp;
    if (jj_scan_token(SCOL)) return true;
    return false;
  }

  private boolean jj_3R_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_6()) {
    jj_scanpos = xsp;
    if (jj_3R_7()) return true;
    }
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(NEW)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(FLOAT)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(OSQBR)) return true;
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_3R_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_23()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(CSQBR)) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_scan_token(LABEL)) return true;
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) return true;
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_8()) {
    jj_scanpos = xsp;
    if (jj_3R_9()) {
    jj_scanpos = xsp;
    if (jj_3R_10()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) return true;
    }
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) return true;
    }
    }
    if (jj_scan_token(VARIABLE)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public CronusGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2800000,0x3c00000,0x0,0x3c00000,0x1c00000,0x0,0x2800000,0xc00,0xc00,0x800,0x400,0xc00,0xc00,0x800,0x400,0xc00,0xc00,0x0,0x0,0x1c000000,0x18000000,0x0,0x3c00000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x2,0x2,0x2,0x2,0x0,0x2,0x2,0x2,0x0,0x2,0x140,0x20,0x0,0x0,0x40,0x0,0x82,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public CronusGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CronusGrammar(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CronusGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public CronusGrammar(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CronusGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public CronusGrammar(CronusGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CronusGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[42];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 42; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
