/* Generated By:JJTree: Do not edit this line. ASTAllParametersNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTAllParametersNode extends SimpleNode {
	
  public ASTAllParametersNode(int id) {
    
	  super(id);
	  
  }

  public ASTAllParametersNode(CronusGrammarParser p, int id) {
    
	  super(p, id);
	  
  }
  
  @Override
  public void interpret() {
	  
	  // TODO: AllParametersNode
	  System.out.println("TODO: AllParametersNode");
	  
  }

}
/* JavaCC - OriginalChecksum=69fb5ac5253a68089cb87350e11a9b74 (do not edit this line) */
