/* Generated By:JJTree: Do not edit this line. ASTAllParametersNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTAllParametersNode extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTAllParametersNode(int id) {

		super(id);

	}

	public ASTAllParametersNode(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {
		
		int k = jjtGetNumChildren();

		switch (k) {
		case 1:
			jjtGetChild(0).interpret();
			break;
		case 3:
			jjtGetChild(0).interpret();
			jjtGetChild(2).interpret();
			break;
		case 5:
			jjtGetChild(0).interpret();
			jjtGetChild(2).interpret();
			jjtGetChild(4).interpret();
			break;
		}

	}
	
	@Override
	public void toGremlin(PrintWriter writer) {
		
		// AllParameters -> NodeLabel ( COMMA NodeDegree ( COMMA NodeProperties)?)?
		//				|	NodeLabel ( COMMA NodeProperties ( COMMA NodeDegree)?)?
		//				|	NodeDegree ( COMMA NodeLabel ( COMMA NodeProperties)?)?
		//				|	NodeDegree ( COMMA NodeProperties ( COMMA NodeLabel)?)?
		//				|	NodeProperties ( COMMA NodeLabel ( COMMA NodeDegree)?)?
		//				|	NodeProperties ( COMMA NodeDegree ( COMMA NodeLabel)?)?
		
		if(!semantic_error) {
			
			int k = jjtGetNumChildren();
			
			if(k == 0)
				writer.println(".V.toList()");
			
			else if(k == 1) {
				
				writer.print(".V.filter{");
				jjtGetChild(0).toGremlin(writer);
				writer.println("}.toList()");
				
			}
			
			else if(k == 3) {
				
				writer.print(".V.filter{");
				jjtGetChild(0).toGremlin(writer);
				writer.print("; ");
				jjtGetChild(2).toGremlin(writer);
				writer.println("}.toList()");
				
			}
			
			else if(k == 5) {
				
				writer.print(".V.filter{");
				jjtGetChild(0).toGremlin(writer);
				writer.print("; ");
				jjtGetChild(2).toGremlin(writer);
				writer.print("; ");
				jjtGetChild(4).toGremlin(writer);
				writer.println("}.toList()");
				
			}

		}
		
	}
	
}
/*
 * JavaCC - OriginalChecksum=69fb5ac5253a68089cb87350e11a9b74 (do not edit this
 * line)
 */
