/* Generated By:JJTree: Do not edit this line. ASTAllParametersNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTAllParametersNode extends SimpleNode {
  public ASTAllParametersNode(int id) {
    super(id);
  }

  public ASTAllParametersNode(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a47c3d749fbce42b2b9f604bda107708 (do not edit this line) */
