/* Generated By:JJTree: Do not edit this line. ASTBreadthSearch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTBreadthSearch extends SimpleNode {
  public ASTBreadthSearch(int id) {
    super(id);
  }

  public ASTBreadthSearch(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1eb8b0daa2679ad437adcfc848639ce (do not edit this line) */
