/* Generated By:JJTree: Do not edit this line. ASTCloseSquareBrackets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTCloseSquareBrackets extends SimpleNode {
  public ASTCloseSquareBrackets(int id) {
    super(id);
  }

  public ASTCloseSquareBrackets(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=792c4e49d70fe18c9055a8c092e82ffd (do not edit this line) */
