/* Generated By:JJTree: Do not edit this line. ASTCompareValues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTCompareValues extends SimpleNode {
  public ASTCompareValues(int id) {
    super(id);
  }

  public ASTCompareValues(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c25104d3e66d72d09aedde5008b1731 (do not edit this line) */
