/* Generated By:JJTree: Do not edit this line. ASTCompareValues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTCompareValues extends SimpleNode {

	public ASTCompareValues(int id) {

		super(id);

	}

	public ASTCompareValues(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		// TODO: alguma verificação que seja necessária
		
	}

}
/*
 * JavaCC - OriginalChecksum=17f3e1f1310d8b3c78d9c2655ab419dc (do not edit this
 * line)
 */
