/* Generated By:JJTree: Do not edit this line. ASTCloseBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTCloseBracket extends SimpleNode {

	public ASTCloseBracket(int id) {

		super(id);

	}

	public ASTCloseBracket(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=9e7769cef22f2a070705db3d9a388764 (do not edit this
 * line)
 */
