/* Generated By:JJTree: Do not edit this line. ASTCloseSquareBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTCloseSquareBracket extends SimpleNode {
  public ASTCloseSquareBracket(int id) {
    super(id);
  }

  public ASTCloseSquareBracket(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6852dcf42494337e6dfcb0ab0a3e1553 (do not edit this line) */
