/* Generated By:JJTree: Do not edit this line. ASTComma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTComma extends SimpleNode {
  public ASTComma(int id) {
    super(id);
  }

  public ASTComma(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f901e699f9bc8b87ea49a8974feb1eed (do not edit this line) */
