/* Generated By:JJTree: Do not edit this line. ASTCloseParenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTCloseParenthesis extends SimpleNode {
  public ASTCloseParenthesis(int id) {
    super(id);
  }

  public ASTCloseParenthesis(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=488db4b48c07209be9544f02b1f201b6 (do not edit this line) */
