/* Generated By:JJTree: Do not edit this line. ASTCompares.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTCompares extends SimpleNode {
  public ASTCompares(int id) {
    super(id);
  }

  public ASTCompares(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf51687c9f23c08d3e50401ab8c4e5bc (do not edit this line) */
