/* Generated By:JJTree: Do not edit this line. ASTDataToCompare.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTDataToCompare extends SimpleNode {
  public ASTDataToCompare(int id) {
    super(id);
  }

  public ASTDataToCompare(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e3c044606b47bb282548f876462c14b (do not edit this line) */
