/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTDeclaration extends SimpleNode {

	public ASTDeclaration(int id) {

		super(id);

	}

	public ASTDeclaration(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		String child_1 = jjtGetChild(1).getVal();

		switch (jjtGetChild(0).toString()) {
		case "Graph":
			if (symtab.containsKey(child_1))
				System.err.println(ErrorConstant.DUPLICATE_ENTRY + child_1 + " of type Graph.");

			else
				symtab.put(child_1, new Graph());

			break;

		case "Edge":
			if (symtab.containsKey(child_1))
				System.err.println(ErrorConstant.DUPLICATE_ENTRY + child_1 + " of type Edge.");

			else
				symtab.put(child_1, new Edge());

			break;

		case "Node":
			if (symtab.containsKey(child_1))
				System.err.println(ErrorConstant.DUPLICATE_ENTRY + child_1 + " of type Node.");

			else
				symtab.put(child_1, new NodeT());

			break;
		}

	}

}
/*
 * JavaCC - OriginalChecksum=236a818438e24a2223330af6f74d3499 (do not edit this
 * line)
 */
