/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTDeclaration extends SimpleNode {
	public ASTDeclaration(int id) {
		super(id);
	}

	public ASTDeclaration(CronusGrammarParser p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=236a818438e24a2223330af6f74d3499 (do not edit this
 * line)
 */
