/* Generated By:JJTree: Do not edit this line. ASTDataToCompare.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTDataToCompare extends SimpleNode {
  public ASTDataToCompare(int id) {
    super(id);
  }

  public ASTDataToCompare(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=850cde2a78453cf677f35e01eb96180b (do not edit this line) */
