/* Generated By:JJTree: Do not edit this line. ASTDegree.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTDegree extends SimpleNode {

	public ASTDegree(int id) {

		super(id);

	}

	public ASTDegree(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=98302961d939daf489fe0ff79b438699 (do not edit this
 * line)
 */
