/* Generated By:JJTree: Do not edit this line. ASTDegree.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTDegree extends SimpleNode {
  public ASTDegree(int id) {
    super(id);
  }

  public ASTDegree(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26a641379cea3d6c377c40142faf5ad2 (do not edit this line) */
