/* Generated By:JJTree: Do not edit this line. ASTDepthSearch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTDepthSearch extends SimpleNode {
  public ASTDepthSearch(int id) {
    super(id);
  }

  public ASTDepthSearch(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1fbed7d149ab2168280b27139ef9baf (do not edit this line) */
