/* Generated By:JJTree: Do not edit this line. ASTDepthSearch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTDepthSearch extends SimpleNode {

	public ASTDepthSearch(int id) {

		super(id);

	}

	public ASTDepthSearch(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=2842f855f3e4f78f1a652f510e0f3e61 (do not edit this
 * line)
 */
