/* Generated By:JJTree: Do not edit this line. ASTEdge.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTEdge extends SimpleNode {
  public ASTEdge(int id) {
    super(id);
  }

  public ASTEdge(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c0f0d5faa1bfbbdb004b9abe31ba4e5 (do not edit this line) */
