/* Generated By:JJTree: Do not edit this line. ASTEdge.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTEdge extends SimpleNode {
  public ASTEdge(int id) {
    super(id);
  }

  public ASTEdge(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95e736603c8ca8d73ed0f0f24478568a (do not edit this line) */
