/* Generated By:JJTree: Do not edit this line. ASTFloat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTFloat extends SimpleNode {
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=895bd8aff585ff7b42f2978528268f87 (do not edit this line) */
