/* Generated By:JJTree: Do not edit this line. ASTGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTGraph extends SimpleNode {
  public ASTGraph(int id) {
    super(id);
  }

  public ASTGraph(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e2ffe8596c0133f31e4c61fd61be420 (do not edit this line) */
