/* Generated By:JJTree: Do not edit this line. ASTGet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTGet extends SimpleNode {
  public ASTGet(int id) {
    super(id);
  }

  public ASTGet(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f4ffbb902bd758aa733ea51b93e03d2 (do not edit this line) */
