/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTInteger extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTInteger(int id) {

		super(id);

	}

	public ASTInteger(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=6f9a19951169215babe1fbaa7a25923d (do not edit this
 * line)
 */
