/* Generated By:JJTree: Do not edit this line. ASTIntervalBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTIntervalBracket extends SimpleNode {
  public ASTIntervalBracket(int id) {
    super(id);
  }

  public ASTIntervalBracket(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4dfb8d49af87bca7294a6a598a328020 (do not edit this line) */
