/* Generated By:JJTree: Do not edit this line. ASTIntervalBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTIntervalBracket extends SimpleNode {
  public ASTIntervalBracket(int id) {
    super(id);
  }

  public ASTIntervalBracket(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf6ef82f3bb3cbadb80dd4c68b794389 (do not edit this line) */
