/* Generated By:JJTree: Do not edit this line. ASTLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTLabel extends SimpleNode {
  public ASTLabel(int id) {
    super(id);
  }

  public ASTLabel(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e8d5c9703c1044bf27fd82128ebfe5b (do not edit this line) */
