/* Generated By:JJTree: Do not edit this line. ASTListNodesRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTListNodesRight extends SimpleNode {
  public ASTListNodesRight(int id) {
    super(id);
  }

  public ASTListNodesRight(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f414a3c519a9e1598dd6bc6bec61f12 (do not edit this line) */
