/* Generated By:JJTree: Do not edit this line. ASTListNodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTListNodes extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTListNodes(int id) {

		super(id);

	}

	public ASTListNodes(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {
		
		// with declaration
		if (jjtGetChild(0).getVal() == null) {

			if (jjtGetNumChildren() < 4) {
				
				jjtGetChild(0).interpret("");

			} else {
				
				String graph = jjtGetChild(2).interpret("");
				jjtGetChild(0).interpret(graph);

			}

		//without declaration
		} else {

			if (symtab.containsKey(jjtGetChild(0).getVal())) {

				if (!(symtab.get(symtab.get(jjtGetChild(0).getVal())) instanceof Graph)) {

					System.out.println(ErrorConstant.INCOMPATIBLE_TYPES + jjtGetChild(0).getVal() + " is not of type NodeList.");
					semantic_error = true;
					return;

				} else {
					
					String graph = jjtGetChild(2).interpret("");
					symtab.put(jjtGetChild(0).getVal(), graph);

				}

			} else {

				System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(0).getVal() + ".");
				semantic_error = true;
				return;

			}

		}

	}

	@Override
	public void toGremlin(PrintWriter writer) {
		
		if(!semantic_error) {
			
		}
		
	}
}
/*
 * JavaCC - OriginalChecksum=8735df251d00f45445747c1ebe0ed7b0 (do not edit this
 * line)
 */
