/* Generated By:JJTree: Do not edit this line. ASTListNodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTListNodes extends SimpleNode {

	public ASTListNodes(int id) {

		super(id);

	}

	public ASTListNodes(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		if (jjtGetChild(0).getVal() == null) {

			if (jjtGetNumChildren() < 4) {

				jjtGetChild(0).interpret();

			} else {

				jjtGetChild(0).interpret();
				jjtGetChild(2).interpret();

			}

		} else {

			if (symtab.containsKey(jjtGetChild(0).getVal())) {

				if (!(symtab.get(jjtGetChild(0).getVal()) instanceof NodeList)) {

					System.out.println(ErrorConstant.INCOMPATIBLE_TYPES + jjtGetChild(0).getVal() + " is not of type NodeList.");
					return;

				} else {

					jjtGetChild(2).interpret();

				}

			} else {

				System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(0).getVal() + ".");
				return;

			}

		}

	}

}
/*
 * JavaCC - OriginalChecksum=8735df251d00f45445747c1ebe0ed7b0 (do not edit this
 * line)
 */
