/* Generated By:JJTree: Do not edit this line. ASTListNodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTListNodes extends SimpleNode {
  public ASTListNodes(int id) {
    super(id);
  }

  public ASTListNodes(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a36df69a5bf2c1908881476e0f88df50 (do not edit this line) */
