/* Generated By:JJTree: Do not edit this line. ASTMoreVars.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public
class ASTMoreVars extends SimpleNode {
	
	public Boolean semantic_error = false;
	
	
  public ASTMoreVars(int id) {
    super(id);
  }

  public ASTMoreVars(CronusGrammarParser p, int id) {
    super(p, id);
  }
  
  @Override
  public String interpret(String moreVars) {
	  
	  String[] nodes2 = null;
	  
	  if(jjtGetChild(0) instanceof ASTVariable)
			nodes2 = (symtab.get(jjtGetChild(0).getVal()).toString()).split("\\[");
	  
	  if(nodes2 != null) {
		  
			if (!symtab.containsKey(nodes2[0])) {

				System.out.println(ErrorConstant.SECOND_NODE_NF + jjtGetChild(0).getVal() + ".");
				semantic_error = true;
				return "semantic_error";

			}
			
			else if(!symtab.containsKey(jjtGetChild(0).getVal())) {
				
				System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(0).getVal() + ".");
				semantic_error = true;
				return "semantic_error";
				
			}
			
	  }
	  else {
			
			if(Integer.parseInt(jjtGetChild(jjtGetNumChildren()-1).getVal().toString()) <= 0) {
				
				System.out.println(ErrorConstant.PATH_SIZE);
				semantic_error = true;
				return "semantic_error";
				
			}
			
	  }
	  
	  if(nodes2 == null) {
		  
		  return "";
		  
	  } else  return nodes2[0];
	  
  }
  
  @Override
  public void toGremlin(PrintWriter writer) {
	  
	  //MoreVars -> VARIABLE | COMP INTEGER | VARIABLE COMMA COMP INTEGER
	  
	  String[] nodes2;
	  String[] index2;
	  
	  if(jjtGetNumChildren() == 1) {
		  
		  nodes2 = (symtab.get(jjtGetChild(0).getVal()).toString()).split("\\[");
		  index2 = nodes2[1].split("]");
		  
		  writer.print("it.object.id != \"" + index2[0] + "\"}.path.toList()");
		  
	  }
	  
	  else if(jjtGetNumChildren() == 2)
		  writer.print("it.loops " + jjtGetChild(0).getVal().toString() + " " 
				  		+ jjtGetChild(1).getVal().toString() + "}.path.toList()");
	  
	  else {
		  
		  nodes2 = (symtab.get(jjtGetChild(0).getVal()).toString()).split("\\[");
		  index2 = nodes2[1].split("]");
		  
		  writer.print("it.object.id != \"" + index2[0] + "\" && it.loops " + jjtGetChild(0).getVal().toString() + " " 
			  		+ jjtGetChild(1).getVal().toString() + "}.path.toList()");
		  
	  }

	  
	  
  }

}
/* JavaCC - OriginalChecksum=6139f18466b12825ad80b26e1a3d45db (do not edit this line) */
