/* Generated By:JJTree: Do not edit this line. ASTMoreOptions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTMoreOptions extends SimpleNode {
  public ASTMoreOptions(int id) {
    super(id);
  }

  public ASTMoreOptions(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61466fe3b3acdc119e264c9aa861d06b (do not edit this line) */
