/* Generated By:JJTree: Do not edit this line. ASTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNode extends SimpleNode {
  public ASTNode(int id) {
    super(id);
  }

  public ASTNode(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70f845bf84ea9c605010c136af2fd3f6 (do not edit this line) */
