/* Generated By:JJTree: Do not edit this line. ASTNewGraphRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNewGraphRight extends SimpleNode {
  public ASTNewGraphRight(int id) {
    super(id);
  }

  public ASTNewGraphRight(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fe69c548ee9a72c4035a4e8be2cd6f6 (do not edit this line) */
