/* Generated By:JJTree: Do not edit this line. ASTNodeListDec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeListDec extends SimpleNode {
  public ASTNodeListDec(int id) {
    super(id);
  }

  public ASTNodeListDec(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8b271c82b7ee7df263c6554c249b040 (do not edit this line) */
