/* Generated By:JJTree: Do not edit this line. ASTNewGraphRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTNewGraphRight extends SimpleNode {

	public ASTNewGraphRight(int id) {

		super(id);

	}

	public ASTNewGraphRight(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

	}

	@Override
	public void toGremlin(PrintWriter writer) {
		
		// TODO: verificar extensão para diferentes tipos de load
		
		// g.loadGraphML('path')
		String path = jjtGetChild(1).getVal().toString();
		
		writer.println(".loadGraphML(\'" + path + "\')");
		
	}
	
}
/*
 * JavaCC - OriginalChecksum=83bebc27370c9bfbae681ebaa3cd842b (do not edit this
 * line)
 */
