/* Generated By:JJTree: Do not edit this line. ASTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNode extends SimpleNode {
  public ASTNode(int id) {
    super(id);
  }

  public ASTNode(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8037f7569397c543562c3db5c82be3a7 (do not edit this line) */
