/* Generated By:JJTree: Do not edit this line. ASTNodeDegree.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeDegree extends SimpleNode {
  public ASTNodeDegree(int id) {
    super(id);
  }

  public ASTNodeDegree(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=124a9063342786335b3ace5037e2f03d (do not edit this line) */
