/* Generated By:JJTree: Do not edit this line. ASTNodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodes extends SimpleNode {
  public ASTNodes(int id) {
    super(id);
  }

  public ASTNodes(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf56cb6a7e54a5e9ae0caf2633018067 (do not edit this line) */
