/* Generated By:JJTree: Do not edit this line. ASTNodeProperties.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeProperties extends SimpleNode {
  public ASTNodeProperties(int id) {
    super(id);
  }

  public ASTNodeProperties(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=600f3a17f5c5510c1aca833f8fb05e81 (do not edit this line) */
