/* Generated By:JJTree: Do not edit this line. ASTNewGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTNewGraph extends SimpleNode {

	public ASTNewGraph(int id) {

		super(id);

	}

	public ASTNewGraph(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		int k = jjtGetNumChildren();
		
		// Graph Variable = NewGraphRight
		if (k >= 5) {

			// Graph
			if (symtab.containsKey(jjtGetChild(1).getVal())) {

				System.err.println(ErrorConstant.DUPLICATE_ENTRY + jjtGetChild(1).getVal() + " of type Graph.");
				return;

			}
			
			else {
				symtab.put(jjtGetChild(1).getVal(), new Graph());
				jjtGetChild(3).interpret();
			}
				

		} else {
			
			// Variable = NewGraphRight
			if (symtab.containsKey(jjtGetChild(0).getVal())) {
	
				if (!(symtab.get(jjtGetChild(0).getVal()) instanceof Graph)) {
	
					System.out.println(ErrorConstant.INCOMPATIBLE_TYPES + jjtGetChild(0).getVal() + " is not of type Graph.");
					return;
	
				}
	
			} else {
	
				System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(0).getVal() + ".");
				return;
	
			}
			
			jjtGetChild(2).interpret();
		}

	}

	@Override
	public void toGremlin(PrintWriter writer) {
		
		String graph = "";
		
		if(jjtGetNumChildren() >= 5) {
			
			graph = jjtGetChild(1).getVal().toString();
			
			String line = graph + " = new TinkerGraph()";
			writer.println(line);
			
			writer.print(graph);
			jjtGetChild(3).toGremlin(writer);
			
		}
			
		else {
			
			graph = jjtGetChild(0).getVal().toString();
			writer.print(graph);
			jjtGetChild(2).toGremlin(writer);
			
		}
		
	}
	
}
/*
 * JavaCC - OriginalChecksum=33fe44e76d5a35d047b507dec2b929c5 (do not edit this
 * line)
 */
