/* Generated By:JJTree: Do not edit this line. ASTNodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTNodes extends SimpleNode {

	public ASTNodes(int id) {

		super(id);

	}

	public ASTNodes(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=e1d18e8591358b1d4aac267198704f8b (do not edit this
 * line)
 */
