/* Generated By:JJTree: Do not edit this line. ASTNodeListDec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeListDec extends SimpleNode {
  public ASTNodeListDec(int id) {
    super(id);
  }

  public ASTNodeListDec(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6243a46c048ed58c0da12f0e90102dc9 (do not edit this line) */
