/* Generated By:JJTree: Do not edit this line. ASTNewGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNewGraph extends SimpleNode {
  public ASTNewGraph(int id) {
    super(id);
  }

  public ASTNewGraph(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f61a54954275af7724e03ace33c7aaf (do not edit this line) */
