/* Generated By:JJTree: Do not edit this line. ASTNodeLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeLabel extends SimpleNode {
  public ASTNodeLabel(int id) {
    super(id);
  }

  public ASTNodeLabel(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=138c5b7e041feaa94c5389c40eb2ea32 (do not edit this line) */
