/* Generated By:JJTree: Do not edit this line. ASTNodeLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTNodeLabel extends SimpleNode {
  public ASTNodeLabel(int id) {
    super(id);
  }

  public ASTNodeLabel(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c670776ef80779731fcd1fc0fcaba6b7 (do not edit this line) */
