/* Generated By:JJTree: Do not edit this line. ASTOpenSquareBracket.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTOpenSquareBracket extends SimpleNode {
  public ASTOpenSquareBracket(int id) {
    super(id);
  }

  public ASTOpenSquareBracket(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73d398bf4e21e3e9dd8ecfc983c69666 (do not edit this line) */
