/* Generated By:JJTree: Do not edit this line. ASTOpenParenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTOpenParenthesis extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTOpenParenthesis(int id) {

		super(id);

	}

	public ASTOpenParenthesis(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=caa3664dacf89c64bf3c2979781778de (do not edit this
 * line)
 */
