/* Generated By:JJTree: Do not edit this line. ASTOpenSquareBrackets.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTOpenSquareBrackets extends SimpleNode {
  public ASTOpenSquareBrackets(int id) {
    super(id);
  }

  public ASTOpenSquareBrackets(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba5d38e1d080da6a7b56922f5ed3a9b0 (do not edit this line) */
