/* Generated By:JJTree: Do not edit this line. ASTOperationDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTOperationDeclaration extends SimpleNode {
  public ASTOperationDeclaration(int id) {
    super(id);
  }

  public ASTOperationDeclaration(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e45c2ee429b71e24ad76c80dd40e040e (do not edit this line) */
