/* Generated By:JJTree: Do not edit this line. ASTOpenParenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTOpenParenthesis extends SimpleNode {
  public ASTOpenParenthesis(int id) {
    super(id);
  }

  public ASTOpenParenthesis(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be54d87f98cf9825eeb687d290cfd8d9 (do not edit this line) */
