/* Generated By:JJTree: Do not edit this line. ASTPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTPath extends SimpleNode {
  public ASTPath(int id) {
    super(id);
  }

  public ASTPath(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f836cd100bc3658fa6e72961a20d8890 (do not edit this line) */
