/* Generated By:JJTree: Do not edit this line. ASTSearchGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTSearchGraph extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTSearchGraph(int id) {

		super(id);

	}

	public ASTSearchGraph(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public String interpret(String searchGraph) {
		
		String[] nodes1 = (symtab.get(jjtGetChild(6).getVal()).toString()).split("\\[");
		String[] nodes2 = (symtab.get(jjtGetChild(8).getVal()).toString()).split("\\[");
		
		if (!symtab.containsKey(nodes1[0])) {

			System.out.println(ErrorConstant.FIRST_NODE_NF + jjtGetChild(0).getVal() + ".");
			semantic_error = true;
			return "semantic_error";

		} else if (!symtab.containsKey(nodes2[0])) {

			System.out.println(ErrorConstant.SECOND_NODE_NF + jjtGetChild(0).getVal() + ".");
			semantic_error = true;
			return "semantic_error";

		}
		
		String g1 = symtab.get(nodes1[0]).toString();
		String g2 = symtab.get(nodes2[0]).toString();
		
		if((!g1.equals(g2)) | (!g1.equals(jjtGetChild(2).getVal().toString()))) {
			
			System.out.println(ErrorConstant.INC_PARA_TYPES);
			semantic_error = true;
			return "semantic_error";
			
		}
		
		// NodeListDec EQ VARIABLE DOT SearchType OPAR VARIABLE COMMA VARIABLE
		// MoreOptions CPAR SCOL
		if(!symtab.containsKey(jjtGetChild(6).getVal())) {
			
			System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(6).getVal() + ".");
			semantic_error = true;
			return "semantic_error";
			
		} else if(!symtab.containsKey(jjtGetChild(8).getVal())) {
			
			System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(8).getVal() + ".");
			semantic_error = true;
			return "semantic_error";
			
		}

		if (jjtGetChild(0) instanceof ASTNodeListDec)
			jjtGetChild(0).interpret(jjtGetChild(2).getVal().toString());

		// VARIABLE EQ VARIABLE DOT SearchType OPAR VARIABLE COMMA VARIABLE
		// MoreOptions CPAR SCOL
		else {

			if (symtab.containsKey(jjtGetChild(0).getVal())) {

				if (!(symtab.containsKey(symtab.get(jjtGetChild(0).getVal())))) {

					System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + symtab.get(jjtGetChild(0).getVal()).toString() + " is not of defined.");
					semantic_error = true;
					return "semantic_error";

				} else {

					symtab.put(jjtGetChild(0).getVal(), jjtGetChild(2).getVal().toString());

					if (!symtab.containsKey(nodes1[0])) {

						System.out.println(ErrorConstant.FIRST_NODE_NF + jjtGetChild(2).getVal() + ".");
						semantic_error = true;
						return "semantic_error";

					} else {

						if (!symtab.containsKey(nodes2[0])) {

							System.out.println(ErrorConstant.SECOND_NODE_NF + jjtGetChild(2).getVal() + ".");
							semantic_error = true;
							return "semantic_error";

						}

					}

				}

			} else {

				System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(0).getVal() + ".");
				semantic_error = true;
				return "semantic_error";

			}

		}

		// Right Side
		verify_graph(2);

		// SearchType
		jjtGetChild(4).interpret();
		
		// MoreOptions
		if(jjtGetChild(9).getVal() != null)
			jjtGetChild(9).interpret();
		
		return "";

	}

	public void verify_graph(Integer i) {

		if (symtab.containsKey(jjtGetChild(i).getVal())) {

			if (!(symtab.get(jjtGetChild(i).getVal()) instanceof Graph)) {

				System.out.println(ErrorConstant.INCOMPATIBLE_TYPES + jjtGetChild(i).getVal() + " is not of type Graph.");
				semantic_error = true;
				return;

			}

		} else {

			System.out.println(ErrorConstant.SYMBOL_NOT_FOUND + jjtGetChild(i).getVal() + ".");
			semantic_error = true;
			return;

		}

	}

	@Override
	public void toGremlin(PrintWriter writer) {
		
		if(!semantic_error) {
		
			// NodeListDec EQ VARIABLE DOT SearchType OPAR VARIABLE COMMA VARIABLE
			String nodeList;
			String graph;
			String node1;
			String node2;
			String searchParameterString = "cenas";
			
			try {
				if (symtab.get(symtab.get(jjtGetChild(0).getVal())) instanceof Graph) {
					
					graph = jjtGetChild(0).getVal().toString();
					node1 = jjtGetChild(5).getVal().toString();
					node2 = jjtGetChild(7).getVal().toString();
					nodeList = "";
				}
			} catch (NullPointerException e) {
				
				graph = jjtGetChild(2).getVal().toString();
				node1 = jjtGetChild(6).getVal().toString();
				node2 = jjtGetChild(8).getVal().toString();
				
				jjtGetChild(0).toGremlin(writer);
				
				writer.print(" = " + graph + ".v(" + node1 + ").out.loop(1){it.object.id != \"" + node2 + "\"}.path");
				
				if (jjtGetChild(9).getVal() == null)
					jjtGetChild(9).toGremlin(writer);
				else
					searchParameterString = "";
				
			}
			
		}
		
	}
}
/*
 * JavaCC - OriginalChecksum=846292d1a956497664ce7a1a19b15629 (do not edit this
 * line)
 */
