/* Generated By:JJTree: Do not edit this line. ASTShortestPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTShortestPath extends SimpleNode {
  public ASTShortestPath(int id) {
    super(id);
  }

  public ASTShortestPath(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=452acd58388945b1c4830821a3fb277a (do not edit this line) */
