/* Generated By:JJTree: Do not edit this line. ASTSemicolon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTSemicolon extends SimpleNode {
  public ASTSemicolon(int id) {
    super(id);
  }

  public ASTSemicolon(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fa4c81d0cc3e6a8c1b87f0a7fe4e78c (do not edit this line) */
