/* Generated By:JJTree: Do not edit this line. ASTSearchType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTSearchType extends SimpleNode {
  public ASTSearchType(int id) {
    super(id);
  }

  public ASTSearchType(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e99717ac172ea1dd18a183a880bb8acb (do not edit this line) */
