/* Generated By:JJTree: Do not edit this line. ASTSearchType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTSearchType extends SimpleNode {

	public ASTSearchType(int id) {

		super(id);

	}

	public ASTSearchType(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		// TODO: alguma verificação que seja necessária
		System.out.println("Type: " + jjtGetChild(0).getVal());
	}

}
/*
 * JavaCC - OriginalChecksum=5b321fcf3da76acbec244789a880317b (do not edit this
 * line)
 */
