/* Generated By:JJTree: Do not edit this line. ASTSearchGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTSearchGraph extends SimpleNode {
  public ASTSearchGraph(int id) {
    super(id);
  }

  public ASTSearchGraph(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a51217502580d732b0c1fe79480d00cf (do not edit this line) */
