/* Generated By:JJTree: Do not edit this line. ASTSemicolon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTSemicolon extends SimpleNode {
  public ASTSemicolon(int id) {
    super(id);
  }

  public ASTSemicolon(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45eb1357b2cdb24eec312208ec038af9 (do not edit this line) */
