/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

import java.io.PrintWriter;

public class ASTValue extends SimpleNode {
	
	public Boolean semantic_error = false;

	public ASTValue(int id) {

		super(id);

	}

	public ASTValue(CronusGrammarParser p, int id) {

		super(p, id);

	}

	@Override
	public void interpret() {

		// TODO: alguma verificação que seja necessária

	}

	@Override
	public void toGremlin(PrintWriter writer) {
		
		// Value -> STRING | INTEGER | FLOAT
		
		writer.print(jjtGetChild(0).getVal().toString());
		
	}
	
}
/*
 * JavaCC - OriginalChecksum=07dcfa71072fe065f3b9da53656575af (do not edit this
 * line)
 */
