/* Generated By:JJTree: Do not edit this line. ASTValues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTValues extends SimpleNode {
  public ASTValues(int id) {
    super(id);
  }

  public ASTValues(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=058c7315e25a7df7b006898cfed71846 (do not edit this line) */
