/* Generated By:JJTree: Do not edit this line. ASTValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTValue extends SimpleNode {
  public ASTValue(int id) {
    super(id);
  }

  public ASTValue(CronusGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3422eda1f7da22b2eac61bae38a4b1d (do not edit this line) */
