/* Generated By:JavaCC: Do not edit this line. CronusGrammarParserTreeConstants.java Version 5.0 */
package main;

public interface CronusGrammarParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDECLARATION = 1;
  public int JJTGRAPH = 2;
  public int JJTEDGE = 3;
  public int JJTNODE = 4;
  public int JJTVARIABLE = 5;
  public int JJTSEMICOLON = 6;
  public int JJTNEWGRAPH = 7;
  public int JJTEQUAL = 8;
  public int JJTNEWGRAPHRIGHT = 9;
  public int JJTNEW = 10;
  public int JJTOPENPARENTHESIS = 11;
  public int JJTPATH = 12;
  public int JJTCLOSEPARENTHESIS = 13;
  public int JJTLISTNODES = 14;
  public int JJTDOT = 15;
  public int JJTNODES = 16;
  public int JJTNODELISTDEC = 17;
  public int JJTOPENSQUAREBRACKET = 18;
  public int JJTCLOSESQUAREBRACKET = 19;
  public int JJTALLPARAMETERSNODE = 20;
  public int JJTCOMMA = 21;
  public int JJTNODELABEL = 22;
  public int JJTLABEL = 23;
  public int JJTNODEDEGREE = 24;
  public int JJTDEGREE = 25;
  public int JJTNODEPROPERTIES = 26;
  public int JJTOPENBRACKET = 27;
  public int JJTCLOSEBRACKET = 28;
  public int JJTVALUE = 29;
  public int JJTSTRING = 30;
  public int JJTINTEGER = 31;
  public int JJTFLOAT = 32;
  public int JJTCOMPAREVALUES = 33;
  public int JJTCOMPARES = 34;
  public int JJTINTERVALBRACKET = 35;
  public int JJTSEARCHGRAPH = 36;
  public int JJTSEARCHTYPE = 37;
  public int JJTSHORTESTPATH = 38;
  public int JJTDEPTHSEARCH = 39;
  public int JJTBREADTHSEARCH = 40;
  public int JJTMOREOPTIONS = 41;
  public int JJTGETNODE = 42;


  public String[] jjtNodeName = {
    "Start",
    "Declaration",
    "Graph",
    "Edge",
    "Node",
    "Variable",
    "Semicolon",
    "NewGraph",
    "Equal",
    "NewGraphRight",
    "New",
    "OpenParenthesis",
    "Path",
    "CloseParenthesis",
    "ListNodes",
    "Dot",
    "Nodes",
    "NodeListDec",
    "OpenSquareBracket",
    "CloseSquareBracket",
    "AllParametersNode",
    "Comma",
    "NodeLabel",
    "Label",
    "NodeDegree",
    "Degree",
    "NodeProperties",
    "OpenBracket",
    "CloseBracket",
    "Value",
    "String",
    "Integer",
    "Float",
    "CompareValues",
    "Compares",
    "IntervalBracket",
    "SearchGraph",
    "SearchType",
    "ShortestPath",
    "DepthSearch",
    "BreadthSearch",
    "MoreOptions",
    "GetNode",
  };
}
/* JavaCC - OriginalChecksum=6af8d7c2443f0d484be409a078997f77 (do not edit this line) */
