/* Generated By:JavaCC: Do not edit this line. CronusGrammarConstants.java */
package main;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CronusGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LOWER = 6;
  /** RegularExpression Id. */
  int UPPER = 7;
  /** RegularExpression Id. */
  int NEW = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int LABEL = 10;
  /** RegularExpression Id. */
  int WEIGHT = 11;
  /** RegularExpression Id. */
  int SHORTESTPATH = 12;
  /** RegularExpression Id. */
  int DEPHSEARCH = 13;
  /** RegularExpression Id. */
  int BREADTHSEARCH = 14;
  /** RegularExpression Id. */
  int IN = 15;
  /** RegularExpression Id. */
  int OUT = 16;
  /** RegularExpression Id. */
  int EDGES = 17;
  /** RegularExpression Id. */
  int NODES = 18;
  /** RegularExpression Id. */
  int GRAPH = 19;
  /** RegularExpression Id. */
  int NODE = 20;
  /** RegularExpression Id. */
  int EDGE = 21;
  /** RegularExpression Id. */
  int VARIABLE = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int INTEGER = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int OPAR = 26;
  /** RegularExpression Id. */
  int CPAR = 27;
  /** RegularExpression Id. */
  int OBR = 28;
  /** RegularExpression Id. */
  int CBR = 29;
  /** RegularExpression Id. */
  int OSQBR = 30;
  /** RegularExpression Id. */
  int CSQBR = 31;
  /** RegularExpression Id. */
  int COL = 32;
  /** RegularExpression Id. */
  int SCOL = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int EQ = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int QUOTE = 37;
  /** RegularExpression Id. */
  int COMP = 38;
  /** RegularExpression Id. */
  int PATH = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<DIGIT>",
    "<LOWER>",
    "<UPPER>",
    "\"new\"",
    "<BOOL>",
    "\"label\"",
    "\"weight\"",
    "\"shortestPath\"",
    "\"dephSearch\"",
    "\"breadthSearch\"",
    "\"in\"",
    "\"out\"",
    "\"edges\"",
    "\"nodes\"",
    "\"Graph\"",
    "\"Node\"",
    "\"Edge\"",
    "<VARIABLE>",
    "<STRING>",
    "<INTEGER>",
    "<FLOAT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "<QUOTE>",
    "<COMP>",
    "<PATH>",
  };

}
