/* Generated By:JavaCC: Do not edit this line. CronusGrammarTreeConstants.java Version 5.0 */
package main;

public interface CronusGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDECLARATION = 1;
  public int JJTGRAPH = 2;
  public int JJTVARIABLE = 3;
  public int JJTSCOL = 4;
  public int JJTEDGE = 5;
  public int JJTNODE = 6;
  public int JJTLISTNODE = 7;
  public int JJTNEWGRAPH = 8;
  public int JJTNEWGRAPHRIGHT = 9;
  public int JJTLISTNODES = 10;
  public int JJTNODELISTDECLARATION = 11;
  public int JJTLISTNODESRIGHT = 12;
  public int JJTALLPARAMETERSNODE = 13;
  public int JJTNODELABEL = 14;
  public int JJTNODEDEGREE = 15;
  public int JJTVALUE = 16;
  public int JJTSEARCHGRAPH = 17;
  public int JJTSEARCHSHORTESTPATH = 18;
  public int JJTDEPTHSEARCH = 19;
  public int JJTBREADTHSEARCH = 20;
  public int JJTNODEPROPERTIES = 21;
  public int JJTCOMPAREVALUES = 22;


  public String[] jjtNodeName = {
    "Start",
    "DECLARATION",
    "GRAPH",
    "VARIABLE",
    "SCOL",
    "Edge",
    "Node",
    "ListNode",
    "NEWGRAPH",
    "NEWGRAPHRIGHT",
    "LISTNODES",
    "NODELISTDECLARATION",
    "LISTNODESRIGHT",
    "ALLPARAMETERSNODE",
    "NodeLabel",
    "NodeDegree",
    "Value",
    "SEARCHGRAPH",
    "SEARCHSHORTESTPATH",
    "DEPTHSEARCH",
    "BREADTHSEARCH",
    "NodeProperties",
    "CompareValues",
  };
}
/* JavaCC - OriginalChecksum=4be85435a35740d7a14ac1e8dc7f0ba1 (do not edit this line) */
