/* Generated By:JJTree: Do not edit this line. ASTPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public class ASTPath extends SimpleNode {

	public Boolean semantic_error = false;
	
	public ASTPath(int id) {

		super(id);

	}

	public ASTPath(CronusGrammarParser p, int id) {

		super(p, id);

	}

}
/*
 * JavaCC - OriginalChecksum=cc4202b6b11570f3e25040178c204308 (do not edit this
 * line)
 */
