/* Generated By:JJTree: Do not edit this line. ASTSearch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main;

public
class ASTSearch extends SimpleNode {
  public ASTSearch(int id) {
    super(id);
  }

  public ASTSearch(CronusGrammarParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=114c18fec10709bc626947aee768c0b5 (do not edit this line) */
